# Use Dockerized infrastructure
sudo: false

language: java

addons:
  sonarcloud:
    organization: "moucho_apps_sonarcloud_key"
  apt:
    packages:
    - default-jre

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - ORGANIZATION_NAME=mouchoapps
    - PROJECT_NAME=moucho-one
    - IMAGE_NAME=hello-world
    - CLUSTER_NAME=cluster-1
    - CLOUDSDK_COMPUTE_ZONE=eu-west1-b
    - NODE_ENV=CI

install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update beta

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

before_deploy:
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./resources/deploy.sh
    skip_cleanup: true
    on:
      branch: master